webapp/config/routes.rb
Webapp::Application.routes.draw do
  get 'register' => 'users#new', :as => 'register'

  get 'login' => 'sessions#index', :as => 'login'

  get 'logout' => 'sessions#destroy', :as => 'logout'

  get 'home' => 'users#index', :as => 'home'

  get 'patients/remove' => 'patients#destroy'

  get 'users/user_patient_selection'

  get 'about' => 'about#index', :as => 'about'

  get 'contact' => 'contact#index', :as => 'contact'

  post 'users/edit_profile' => 'users#update'

  root :to => "sessions#index"

  resources :users, :path => 'register', :only => ['new', 'create']

  resources :users, :path => 'users'

  resources :patients

  resources :prescriptions

  resources :notes

  resources :sessions, :path => 'login'

end

webapp/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :last_name, :first_name, :phone, :address, :usertype, :avatar

  has_many :associations, :dependent => :restrict
  has_many :patients, :through => :associations

  attr_accessor :password
  before_save :encrypt_password

  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :last_name
  validates_presence_of :first_name
  validates_presence_of :phone
  validates_uniqueness_of :phone
  validates_presence_of :address
  validates_presence_of :usertype
  validates_inclusion_of :usertype, :in => ['Guardian', 'Care taker', 'Doctor']
  validates_presence_of :avatar

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

webapp/app/views/shared/_add_note_modal_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="addNote">New Note</h3>
</div>
<%= form_tag '/notes', :method => 'post', :class => 'no-tail', :id => 'add-note-form' do %>
<% if controller.controller_name=='patients' %>
  <div class="error_messages">
    <% if @patient.errors.any? %>
    <ul>
      <% for message in @patient.errors.full_messages %>
        <li class="text-error"><%= message %></li>
      <% end %>
    </ul>
    <% end %>
  </div>
<% else %>
  <div class="error_messages"></div>
<% end %>
  <div class="modal-body">
    <%= text_area_tag 'note[content]', nil, :rows => 6, :class=>"span9", :required => true %>
    <%= hidden_field_tag 'note[patient_id]', nil %>
    <%= hidden_field_tag 'note[author_id]', session[:user_id] %>
    <!-- <span class="span3 pull-right"><img class="img-rounded" src="/assets/avatars/dp8.jpg" alt="" /></span> -->
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <%= button_tag 'Add', :type => 'submit', :class => 'btn btn-primary' %>
  </div>
<% end %>

webapp/app/views/shared/_add_patient_modal_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="addPatient">New Patient</h3>
</div>
<%= form_tag '/patients', :method => 'post', :class => 'no-tail', :id => 'add-patient-form' do %>
<% if controller.controller_name=='patients' %>
  <div class="error_messages">
    <% if @patient.errors.any? %>
    <ul>
      <% for message in @patient.errors.full_messages %>
        <li class="text-error"><%= message %></li>
      <% end %>
    </ul>
    <% end %>
  </div>
<% else %>
  <div class="error_messages"></div>
<% end %>
  <div class="modal-body">
    <div class="span9" id="add-patient-form-fields">
      <span class="span12">
        <%= label_tag :patient_first_name, 'First Name:', :class => 'form-label span4' %>
        <%= text_field_tag 'patient[first_name]', '', :class => 'input-block-level span8', :required => true %>
      </span>
      <span class="span12">
        <%= label_tag :patient_last_name, 'Last Name:', :class => 'form-label span4' %>
        <%= text_field_tag 'patient[last_name]', '', :class => 'span8', :required => true %>
      </span>
      <span class="span12">
        <label class="form-label span4">Gender:</label>
        <label class="radio inline span4">
          <%= radio_button_tag 'patient[gender]', 'Male', :checked => true %>
          Male
        </label>
        <label class="radio inline span4">
          <%= radio_button_tag 'patient[gender]', 'Female' %>
          Female
        </label>
      </span>
      <span class="span12">
        <%= label_tag :patient_age, 'Age:', :class => 'form-label span4' %>
        <%= number_field_tag 'patient[age]', nil, :in => 1..100, :class => 'span8', :required => true %>
      </span>
      <span class="span12">
        <%= label_tag :patient_phone, 'Phone:', :class => 'form-label span4' %>
        <%= text_field_tag 'patient[phone]', '', :placeholder => '(xxx) xxx-xxxx', :class => 'span8', :required => true %>
      </span>
      <span class="span12">
        <%= label_tag :patient_address, 'Address:', :class => 'form-label span4' %>
        <%= text_field_tag 'patient[address]', '', :placeholder => '123 aname st, city, province', :class => 'span8', :required => true %>
      </span>
      <span class="span12">
        <%= label_tag :patient_health_status, 'Health Status:', :class => 'form-label span4' %>
        <%= select_tag 'patient[health_status]', '<option value="Healthy">Healthy</option><option value="Sub-healthy">Sub-healthy</option><option value="Ill">Ill</option><option value="Passed away">Passed away</option>'.html_safe, :class => 'span8' %>
      </span>
      <span class="span12">
        <%= label_tag :patient_symptoms, 'Symptoms:', :class => 'form-label span4' %>
        <%= text_area_tag 'patient[symptoms]', nil, :rows => 3, :class => 'no-tail span8', :required => true %>
      </span>
    </div>
    <div class="span3" id="add-patient-avatar-selection" style="overflow-x: hidden; overflow-y: auto;">
        <%= hidden_field_tag 'patient[avatar]', '/assets/avatars/dp_default.jpg' %>
        <img class="img-select img-rounded" src="/assets/avatars/dp0.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp1.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp2.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp3.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp4.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp5.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp6.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp7.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp8.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp9.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp10.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp11.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp12.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp13.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp14.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp15.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp16.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp17.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp18.jpg" />
        <img class="img-select img-rounded" src="/assets/avatars/dp19.jpg" />
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <%= button_tag 'Add', :type => 'submit', :class => 'btn btn-primary' %>
  </div>
<% end %>

webapp/app/views/shared/_add_prescription_modal_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="addPrescription">New Prescription</h3>
</div>
<%= form_tag '/prescriptions', :method => 'post', :class => 'no-tail', :id => 'add-prescription-form' do %>
<!--
<% if controller.controller_name=='prescriptions' %>
  <div class="error_messages">
    <% if @prescription.errors.any? %>
    <ul>
      <% for message in @prescription.errors.full_messages %>
        <li class="text-error"><%= message %></li>
      <% end %>
    </ul>
    <% end %>
  </div>
<% else %>
  <div class="error_messages"></div>
<% end %>
-->
  <div class="modal-body">
    <span class="span12">
      <label class="form-label span3">Select Pill:</label>   
      <%= select_tag "prescription[pill_name]", options_from_collection_for_select(@allPills, "id", "name") %>
    </span>
    <span class="span12">
       <label class="form-label span3">Direction:</label>
       <%= text_area_tag 'prescription[direction]', nil, :rows => 3, :required => true %>
    </span>
    <span class="span12">
      <label class="form-label span3">Start Date:</label>
      <div class="input-append date" id="prescription-date-start">
        <input class="special-place span3" id="prescription_start_date" name="prescription[start_date]" size="16" type="text" value="00-00-0000" readonly>
        <span class="add-on"><i class="icon-calendar"></i></span>
      </div>
    </span>
    <span class="span12">
      <label class="form-label span3">End Date:</label>
      <div class="input-append date" id="prescription-date-end">
        <input class="special-place span3" id="prescription_end_date" name="prescription[end_date]" size="16" type="text" value="00-00-0000" readonly>
        <span class="add-on"><i class="icon-calendar"></i></span>
      </div>
    </span>
    <span class="span12">
      <label class="form-label span3">Frenquency:</label>
      <%= select_tag 'prescription[servings_per_day]', '<option value=1>1 time per day</option><option value=2>2 times per day</option><option value=3>3 times per day</option>'.html_safe %>            
    </span>
    <span class="span12">
      <label class="form-label span3">Quantity:</label> 
      <%= select_tag 'prescription[quantities_per_serving]', '<option value=1>1 pill per serving</option><option value=2>2 pills per serving</option><option value=3>3 pills per serving</option><option value=4>4 pills per serving</option>'.html_safe %>
    </span>
    <%= hidden_field_tag 'prescription[patient_id]', nil %>
    <%= hidden_field_tag 'prescription[doctor_id]', session[:user_id] %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <%= button_tag 'Add', :type => 'submit', :class => 'btn btn-primary' %>
  </div>
<% end %>

webapp/app/views/shared/_display_caretaker_patient_selection_sidebar.erb
<ul class="nav nav-list" id="patient-selection">
  <li class="nav-header">Patient Administration</li>
  <li class="divider"></li>
  <!-- Button to trigger add patient modal -->
  <!--<li><a href="#add-patient-modal" id="add-patient-btn" class="btn">Add a new patient</a></li>-->
  <!-- Add patient modal -->
  <!--<div id="add-patient-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="addPatient" aria-hidden="true">-->
    <!--<%= render 'shared/add_patient_modal_form' %>-->
  <!--</div>&lt;!&ndash;/modal &ndash;&gt;-->
  <% @patient.each do |_patient| %>
  <li class="patient-list"><a><%= _patient.first_name %>&nbsp;<%= _patient.last_name %></a></li>
  <% end %>
  <!-- Button to trigger remove patient modal -->
  <!--<li><a href="#remove-patient" id="remove-patient-btn" class="btn">Remove patients</a></li>-->
  <!--&lt;!&ndash; Remove patient modal &ndash;&gt;-->
  <!--<div id="remove-patient-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="removePatient" aria-hidden="true">-->
    <!--<%= render 'shared/remove_patient_modal_form' %>-->
  <!--</div>&lt;!&ndash;/modal &ndash;&gt;-->
</ul>

webapp/app/views/shared/_display_doctor_patient_administration_box.erb
<div class="tabbable" id="patient-administration" style="display: none;"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs bordered" id="action-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Notes</a></li>
    <li><a href="#tab2" data-toggle="tab">Prescription</a></li>
    <li>
      <a href="#tab3" data-toggle="tab">
        <i class="hidden-phone">Primary Contact</i>
        <i class="visible-phone">Contact</i>
      </a>
    </li>
  </ul>
  <div class="tab-content well bordered">
    <div class="tab-pane fade in active" id="tab1">
      <!-- Button to trigger add note modal -->
      <a href="#add-note" id="add-note-btn" class="btn btn-primary">Add New Note</a>
      <!-- Add note modal -->
      <div id="add-note-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="addNote" aria-hidden="true">
        <%= render 'shared/add_note_modal_form' %>
      </div><!--/modal -->
      <ul class="nav nav-tabs nav-stacked no-tail slider-tab" id="patient-notes"></ul>
    </div>
    <div class="tab-pane fade in" id="tab2">
      <!-- Button to trigger add prescription modal -->
      <a href="#add-prescription" id="add-prescription-btn" class="btn btn-primary force-tail">Add Prescription Note</a>
      <!-- Add prescription modal -->
      <div id="add-prescription-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="addPrescription" aria-hidden="true">
        <%= render 'shared/add_prescription_modal_form' %>
      </div><!--/modal -->
      <ul class="nav nav-tabs nav-stacked no-tail slider-tab">
        <li class="active">
          <a class="clearfix">
            <span class="pull-left"><b>Current Prescription</b></span>
            <span class="pull-right"></span>
            <br>
            <div id="prescription-list">
            </div>
          </a>
        </li>
      </ul>
    </div>
    <div class="tab-pane fade in" id="tab3">
      <div class="well well-small no-tail bg-eee clearfix">
        <div class="span3">
          <img class="img-rounded" src="/assets/avatars/dp10.jpg" alt="" />
        </div>
        <div class="span9">
          <span class="span12">
            <label class="form-label span2">First Name:</label>
            <input class="" type="text" readonly value="" />
          </span>
          <span class="span12">
            <label class="form-label span2">Last Name:</label>
            <input class="" type="text" readonly value="" />
          </span>
          <span class="span12">
            <label class="form-label span2">Gender:</label>
            <span class="force-tail">
              <label class="radio inline span2">
                <input type="radio" name="gender" disabled="disabled"  />
                Male
              </label>
              <label class="radio inline span2">
                <input type="radio" name="gender" disabled="disabled" checked="checked"/>
                Female
              </label>
            </span>
          </span>
          <span class="span12">
            <label class="form-label span2">Phone:</label>
            <input class="" type="text" readonly value="" />
          </span>
          <span class="span12">
            <label class="form-label span2">Address:</label>
            <input class="" type="text" readonly value="" />
          </span>
        </div>
      </div>
    </div>
  </div>
</div>

webapp/app/views/shared/_display_doctor_patient_selection_sidebar.erb
<ul class="nav nav-list" id="patient-selection">
  <li class="nav-header">Patient Administration</li>
  <li class="divider"></li>
  <!-- Button to trigger add patient modal -->
  <!--<li><a href="#add-patient-modal" id="add-patient-btn" class="btn">Add a new patient</a></li>-->
  <!-- Add patient modal -->
  <!--<div id="add-patient-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="addPatient" aria-hidden="true">-->
    <!--<%= render 'shared/add_patient_modal_form' %>-->
  <!--</div>&lt;!&ndash;/modal &ndash;&gt;-->
  <% @patient.each do |_patient| %>
  <li class="patient-list"><a><%= _patient.first_name %>&nbsp;<%= _patient.last_name %></a></li>
  <% end %>
  <!-- Button to trigger remove patient modal -->
  <!--<li><a href="#remove-patient" id="remove-patient-btn" class="btn">Remove patients</a></li>-->
  <!-- Remove patient modal -->
  <!--<div id="remove-patient-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="removePatient" aria-hidden="true">-->
    <!--<%= render 'shared/remove_patient_modal_form' %>-->
  <!--</div>&lt;!&ndash;/modal &ndash;&gt;-->
</ul>

webapp/app/views/shared/_display_guardian_patient_selection_sidebar.erb
<ul class="nav nav-list" id="patient-selection">
  <li class="nav-header">Patient Administration</li>
  <li class="divider"></li>
  <!-- Button to trigger add patient modal -->
  <li><a href="#add-patient" id="add-patient-btn" class="btn">Add a new patient</a></li>
  <!-- Add patient modal -->
  <div id="add-patient-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="addPatient" aria-hidden="true">
    <%= render 'shared/add_patient_modal_form' %>
  </div><!--/modal -->
  <% @patient.each do |_patient| %>
  <li class="patient-list"><a><%= _patient.first_name %>&nbsp;<%= _patient.last_name %></a></li>
  <% end %>
  <!-- Button to trigger remove patient modal -->
  <li><a href="#remove-patient" id="remove-patient-btn" class="btn">Remove patients</a></li>
  <!-- Remove patient modal -->
  <div id="remove-patient-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="removePatient" aria-hidden="true">
    <%= render 'shared/remove_patient_modal_form' %>
  </div><!--/modal -->
</ul>

webapp/app/views/shared/_display_patient_administration_box.erb
<div class="tabbable" id="patient-administration" style="display: none;"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs bordered" id="action-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Notes</a></li>
    <li><a href="#tab2" data-toggle="tab">Prescription</a></li>
    <li>
      <a href="#tab3" data-toggle="tab">
        <i class="hidden-phone">Primary Contact</i>
        <i class="visible-phone">Contact</i>
      </a>
    </li>
  </ul>
  <div class="tab-content well bordered">
    <div class="tab-pane fade in active" id="tab1">
      <!-- Button to trigger add note modal -->
      <a href="#add-note" id="add-note-btn" class="btn btn-primary">Add New Note</a>
      <!-- Add note modal -->
      <div id="add-note-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="addNote" aria-hidden="true">
        <%= render 'shared/add_note_modal_form' %>
      </div><!--/modal -->
      <ul class="nav nav-tabs nav-stacked no-tail slider-tab" id="patient-notes"></ul>
    </div>
    <div class="tab-pane fade in" id="tab2">
      <% if session[:user_type]=='Doctor' %>
      <!-- Button to trigger add prescription modal -->
      <a href="#add-prescription" id="add-prescription-btn" class="btn btn-primary force-tail">Add Prescription Note</a>
      <!-- Add prescription modal -->
      <div id="add-prescription-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="addPrescription" aria-hidden="true">
        <%= render 'shared/add_prescription_modal_form' %>
      </div><!--/modal -->
      <% end %>
      <ul class="nav nav-tabs nav-stacked no-tail slider-tab" id="patient-prescriptions"></ul>
    </div>
    <div class="tab-pane fade in" id="tab3">
      <div class="well well-small no-tail bg-eee clearfix">
        <div class="span3">
          <img class="img-rounded" src="/assets/avatars/dp10.jpg" alt="" />
        </div>
        <div class="span9">
          <span class="span12">
            <label class="form-label span2">First Name:</label>
            <input class="" type="text" readonly value="" />
          </span>
          <span class="span12">
            <label class="form-label span2">Last Name:</label>
            <input class="" type="text" readonly value="" />
          </span>
          <span class="span12">
            <label class="form-label span2">Gender:</label>
            <span class="force-tail">
              <label class="radio inline span2">
                <input type="radio" name="gender" disabled="disabled"  />
                Male
              </label>
              <label class="radio inline span2">
                <input type="radio" name="gender" disabled="disabled" checked="checked"/>
                Female
              </label>
            </span>
          </span>
          <span class="span12">
            <label class="form-label span2">Phone:</label>
            <input class="" type="text" readonly value="" />
          </span>
          <span class="span12">
            <label class="form-label span2">Address:</label>
            <input class="" type="text" readonly value="" />
          </span>
        </div>
      </div>
    </div>
  </div>
</div>

webapp/app/views/shared/_display_patient_info_box.erb
<div class="well clearfix" id="patient-info" style="display: none;">
  <div class="span7" id="patient-data">

    <h4 id="patient-name-display"></h4>

    <div class="span12 no-margin">
      <dl class="span9" id="patient-status">

        <dd class="clearfix"><span class="label label-info">Doctor:</span></dd>
        <div id="doctor-list">
        </div>

        <dd class="clearfix"><span class="label label-info">Web Service Test:</span></dd>
        <div id="test_push">
          <dd class="clearfix">
            <a href="http://capstone.dyndns.biz:8000">Go To Push Test</a>
          </dd>
        </div>
        <div id="test_pull">
          <dd class="clearfix">
            <a href="http://capstone.dyndns.biz:8000/pull/170">Pull Patient Status Data</a>
          </dd>
        </div>

        <dd class="clearfix"><span class="label label-info">Recent Heart Rates:</span></dd>
        <dd class="clearfix">
          <span class="" id="heartRate_date"></span>
          <span class="label pull-right patient-status-row" id="heartRate"></span>
        </dd>
        <dd class="clearfix"><span class="label label-info">Heath Status:</span><span id="patient-health-status" class="label pull-right patient-status-row"></span></dd>
        <dd class="clearfix"><span class="label label-info">Fall Status:</span><span class="label pull-right patient-status-row">loading...</span></dd>
        <dd class="clearfix"><span class="label label-info">Last Missed Medication:</span><span class="label pull-right patient-status-row">loading...</span></dd>
      </dl>
      <div class="span3">
        <img class="img-rounded" id="patient-profile-avatar" alt="" />
      </div>
    </div>
    <span class="visible-phone"><br /></span>
    <dl class="span12 no-margin" id="patient-profile">
      <dd><span class="label label-inverse">Name:</span><span class="label pull-right patient-profile-name">loading...</span></dd>
      <dd><span class="label label-inverse">Gender:</span><span class="label pull-right patient-profile-gender">loading...</span></dd>
      <dd><span class="label label-inverse">Age:</span><span class="label pull-right patient-profile-age">loading...</span></dd>
      <dd><span class="label label-inverse">Phone #:</span><span class="label pull-right patient-profile-phone">loading...</span></dd>
      <dd><span class="label label-inverse">Address:</span><span class="label label-limit-width pull-right patient-profile-address" id="gmap_address">loading...</span></dd>
      <dd><span class="label label-inverse">Symptoms:</span><span class="label label-limit-width pull-right patient-profile-symptoms" readonly>loading...</span></dd>
    </dl>
  </div>
  <div class="span5" id="patient-gmap">
    <div class="hidden-phone" id="map_canvas"></div>
  </div>
</div>
<div class="well clearfix" id="patient-info-empty" style="display: none;">
  <div class="clearfix">
    <img class="img-rounded" src="/assets/patient-info-empty.jpg" alt="" />
  </div>
</div>

webapp/app/views/shared/_display_patient_selection_sidebar.erb
<ul class="nav nav-list" id="patient-selection">
  <li class="nav-header">Patient Administration</li>
  <li class="divider"></li>
  <!-- Button to trigger add patient modal -->
  <li><a href="#add-patient-modal" id="add-patient-btn" class="btn">Add a new patient</a></li>
  <!-- Add patient modal -->
  <div id="add-patient-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="addPatient" aria-hidden="true">
    <%= render 'shared/add_patient_modal_form' %>
  </div><!--/modal -->
  <% @patient.each do |_patient| %>
  <li class="patient-list"><a><%= _patient.first_name %>&nbsp;<%= _patient.last_name %></a></li>
  <% end %>
  <!-- Button to trigger remove patient modal -->
  <li><a href="#remove-patient" id="remove-patient-btn" class="btn">Remove patients</a></li>
  <!-- Remove patient modal -->
  <div id="remove-patient-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="removePatient" aria-hidden="true">
    <%= render 'shared/remove_patient_modal_form' %>
  </div><!--/modal -->
</ul>

webapp/app/views/shared/_remove_patient_modal_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="removePatients">Remove Patients</h3>
</div>
<%= form_tag '/patients/remove', :method => 'delete', :class => 'no-tail', :id => 'remove-patient-form' do %>
  <div class="modal-body">
    <span class="span12">
      <%= label_tag :patient_ids, 'Select multiple patients:', :class => 'form-label span4' %>
      <%= select_tag :patient_ids, '', :multiple => true, :id => 'remove-patient-select' %>
    </span>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <%= button_tag 'Remove', :type => 'submit', :class => 'btn btn-primary' %>
  </div>
<% end %>